[package]
name = "quest"
version = "0.2.0"
authors = ["Sam Westerman <sam@sampersand.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
