[package]
name = "bytecode"
version = "0.1.0"
authors = ["Sam Westerman <sam@sampersand.me>"]
edition = "2018"

[dependencies]
quest-core = { path = "../core" }
bitflags = "1.2"
static_assertions = "1.1.0"
