[package]
name = "quest-parser"
version = "0.1.0"
authors = ["Sam Westerman <sam@sampersand.me>"]
edition = "2018"

[dependencies]
quest-core = { path = "../core" }

[dev-dependencies]
tempfile = "3.1"