[package]
name = "quest-parser"
version = "0.2.0"
authors = ["Sam Westerman <sam@sampersand.me>"]
edition = "2018"

[dependencies]
quest-core = { path = "../core" }
regex = "1.3"
lazy_static = "*"

[dev-dependencies]
tempfile = "3.1"
