name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:

  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - uses: hecrj/setup-rust-action@v1
        with:
          rust-version: nightly

      - name: Build
        run: cargo build --workspace --all-targets --verbose

      - name: Run tests
        run: cargo test --workspace --all-targets --verbose

      # Workaround for https://github.com/rust-lang/cargo/issues/6669
      - name: Run doctests
        run: cargo test --workspace --docs --verbose

